export const COUNTRY_LIST = [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Côte d\'Ivoire', 'Cabo Verde', 
    'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)', 
    'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia (Czech Republic)', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 
    'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini (fmr. "Swaziland")', 'Ethiopia', 'Fiji', 'Finland', 
    'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 
    'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 
    'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 
    'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 
    'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 
    'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (formerly Burma)', 'Namibia', 
    'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 
    'Oman', 'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 
    'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 
    'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 
    'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 
    'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 
    'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 
    'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
];

export const TIMEZONE_LIST = [
    { name: "(GMT -12:00) Eniwetok, Kwajalein", value: "-12:00"},
    { name: "(GMT -11:00) Midway Island, Samoa", value: "-11:00"},
    { name: "(GMT -10:00) Hawaii", value: "-10:00"},
    { name: "(GMT -9:30) Taiohae", value: "-09:50"},
    { name: "(GMT -9:00) Alaska", value: "-09:00"},
    { name: "(GMT -8:00) Pacific Time (US &amp; Canada)", value: "-08:00"},
    { name: "(GMT -7:00) Mountain Time (US &amp; Canada)", value: "-07:00"},
    { name: "(GMT -6:00) Central Time (US &amp; Canada), Mexico City", value: "-06:00"},
    { name: "(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima", value: "-05:00"},
    { name: "(GMT -4:30) Caracas", value: "-04:50"},
    { name: "(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz", value: "-04:00"},
    { name: "(GMT -3:30) Newfoundland", value: "-03:50"},
    { name: "(GMT -3:00) Brazil, Buenos Aires, Georgetown", value: "-03:00"},
    { name: "(GMT -2:00) Mid-Atlantic", value: "-02:00"},
    { name: "(GMT -1:00) Azores, Cape Verde Islands", value: "-01:00" },
    { name: "(GMT) Western Europe Time, London, Lisbon, Casablanca", value: "+00:00"},
    { name: "(GMT +1:00) Brussels, Copenhagen, Madrid, Paris", value: "+01:00"},
    { name: "(GMT +2:00) Kaliningrad, South Africa", value: "+02:00"},
    { name: "(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg", value: "+03:00"},
    { name: "(GMT +3:30) Tehran", value: "+03:50"},
    { name: "(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi", value: "+04:00"},
    { name: "(GMT +4:30) Kabul", value: "+04:50"},
    { name: "(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent", value: "+05:00"},
    { name: "(GMT +5:30) Bombay, Calcutta, Madras, New Delhi", value: "+05:50"},
    { name: "(GMT +5:45) Kathmandu, Pokhara", value: "+05:75"},
    { name: "(GMT +6:00) Almaty, Dhaka, Colombo", value: "+06:00"},
    { name: "(GMT +6:30) Yangon, Mandalay", value: "+06:50"},
    { name: "(GMT +7:00) Bangkok, Hanoi, Jakarta", value: "+07:00"},
    { name: "(GMT +8:00) Beijing, Perth, Singapore, Hong Kong", value: "+08:00"},
    { name: "(GMT +8:45) Eucla", value: "+08:75"},
    { name: "(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk", value: "+09:00"},
    { name: "(GMT +9:30) Adelaide, Darwin", value: "+09:50"},
    { name: "(GMT +10:00) Eastern Australia, Guam, Vladivostok", value: "+10:00"},
    { name: "(GMT +10:30) Lord Howe Island", value: "+10:50"},
    { name: "(GMT +11:00) Magadan, Solomon Islands, New Caledonia", value: "+11:00"},
    { name: "(GMT +11:30) Norfolk Island", value: "+11:50"},
    { name: "(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka", value: "+12:00"},
    { name: "(GMT +12:45) Chatham Islands", value: "+12:75"},
    { name: "(GMT +13:00) Apia, Nukualofa", value: "+13:00"},
    { name: "(GMT +14:00) Line Islands, Tokelau", value: "+14:00"}
];
export const EMPLOYEE_CATE_STATUS = ['N/A', 'Person with Disability (PWD)', 'Refugee','Members of the minority community (abused)', 'Senior Citizen', 'Oppressed Environment', 'Person with Comorbidity'];
export const EMPLOYEE_MARITAL_STATUS = ['Married/Partnered', 'Single','Others'];
export const EMPLOYEE_GENDER = ['Male','Female','Others'];
export const EMPLOYEE_STATUS = [{ name: "Active", value: "1"}, { name: "Inactive", value: "0"}];
export const DEFAULT_AVATAR = 'storage/images/avatars/no_image.jpg';